// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzbmbzpcgjjrjwivxdif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6Ym1ienBjZ2pqcmp3aXZ4ZGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5OTMzNjIsImV4cCI6MjA3MzU2OTM2Mn0.pDjL0NMFz9gtlc4TTzjt5kSIflbHNa2KAHB_-cZm7Ro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});